@echo off
echo Starting Konsultabot Django Backend...
cd /d "c:\Users\Ace Ziegfred Culapas\CascadeProjects\CapProj"
call ".venv\Scripts\activate.bat"
echo Installing dependencies...
pip install -r requirements.txt
cd backend
echo Running migrations...
python manage.py migrate
echo Starting Django server on 0.0.0.0:8000...
python manage.py runserver 0.0.0.0:8000
pause
