// sync_ngrok_url.js
// Usage: node sync_ngrok_url.js (run from project root or from backend folder via starter scripts)
// It expects backend/.ngrok-last-url to exist with a single line containing the ngrok HTTPS URL.

const fs = require('fs');
const path = require('path');

const backendDir = path.resolve(__dirname);
const ngrokFile = path.join(backendDir, '.ngrok-last-url');

if (!fs.existsSync(ngrokFile)) {
  console.error('ngrok url file not found:', ngrokFile);
  process.exit(1);
}

const ngrokUrl = fs.readFileSync(ngrokFile, 'utf8').trim();
if (!ngrokUrl) {
  console.error('ngrok url file is empty');
  process.exit(1);
}
console.log('Ngrok URL read:', ngrokUrl);

// Path to mobile app config (adjust if your mobile project stores config elsewhere)
const mobileConfigPath = path.resolve(__dirname, '..', 'KonsultabotMobileNew', 'app_config', 'api_base_url.js');

// Ensure directory exists
const mobileConfigDir = path.dirname(mobileConfigPath);
if (!fs.existsSync(mobileConfigDir)) {
  fs.mkdirSync(mobileConfigDir, { recursive: true });
}

const fileContents = `// AUTO-GENERATED by sync_ngrok_url.js - DO NOT EDIT MANUALLY
export const API_BASE_URL = "${ngrokUrl}";

`;

fs.writeFileSync(mobileConfigPath, fileContents, 'utf8');
console.log('Wrote mobile API config to:', mobileConfigPath);

// Optional: print sample usage
console.log('Done. In your mobile code import API_BASE_URL from "./app_config/api_base_url"');

