# Generated by Django 4.2.7 on 2025-12-09 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('enrollment', 'Enrollment'), ('academics', 'Academics'), ('schedule', 'Schedule'), ('facilities', 'Facilities'), ('financial', 'Financial'), ('services', 'Services'), ('campus', 'Campus'), ('general', 'General'), ('technical', 'Technical Support'), ('personal', 'Personal Query')], default='general', max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('language', models.CharField(choices=[('english', 'English'), ('bisaya', 'Bisaya'), ('waray', 'Waray'), ('tagalog', 'Tagalog')], default='english', max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for matching')),
                ('confidence_score', models.FloatField(default=0.8, help_text='Confidence score based on usage')),
                ('usage_count', models.IntegerField(default=1, help_text='Number of times this Q&A was used')),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='chat', help_text='Source: chat, manual, imported', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this entry was used for a response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge_base', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-usage_count', '-last_used_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='chat_userkn_user_id_1fced1_idx'), models.Index(fields=['user', 'category'], name='chat_userkn_user_id_6a41b9_idx'), models.Index(fields=['user', 'language'], name='chat_userkn_user_id_00ed55_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
