# Generated by Django 4.2.7 on 2025-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
